name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Login Docker
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push image docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            isadoraxavierr/review-filmes:v${{ github.run_number }}
            isadoraxavierr/review-filmes:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Configure EKS
        run: aws eks update-kubeconfig --name aula-eks
      - name: Deploy EKS AWS
        uses: Azure/k8s-deploy@v5.0.0
        with:
           manifests: |
              ./k8s/deployment.yaml
           images: |
              'isadoraxavierr/review-filmes:v${{ event.run_id }}'
        
    
